[build]
  command = "npm run build"
  publish = ".next"

[template]
  incoming-hooks = ["WixBookings"]

[template.environment]
  BOOKINGS_API_KEY = "Wix API Key: manage.wix.com/account/api-keys"
  BOOKINGS_SITE_ID = "The site id to use"
  NEXT_PUBLIC_BOOKINGS_CHECKOUT_URL = "The url of the Bookings form page in the live site"
